version: 2

models:
  - name: mart_order
    description: "This table has basic information about orders, as well as some derived facts based on payments."
    columns:
      - name: ship_mode
        description: '{{ doc("orders_ship_mode") }}'
      - name: customer_id
        description: "Foreign key referencing the customer_id in dim_customer."
        tests:
          - relationships:
              to: ref('dim_customer')
              field: customer_id
      - name: product_id
        description: "Foreign key referencing the product_id in dim_product."
        tests:
          - relationships:
              to: ref('dim_product')
              field: product_id

  - name: dim_customer
    description: "Dimension table containing customer information."
    columns:
      - name: customer_id
        description: "Primary key for customers."

  - name: dim_product
    description: "Dimension table containing product information."
    columns:
      - name: product_id
        description: "Primary key for products."

  - name: fact_sales
    description: "Fact table containing sales transactions."
    columns:
      - name: customer_id
        description: "Foreign key referencing customer_id in dim_customer."
        tests:
          - relationships:
              to: ref('dim_customer')
              field: customer_id
      - name: product_id
        description: "Foreign key referencing product_id in dim_product."
        tests:
          - relationships:
              to: ref('dim_product')
              field: product_id





