# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'ag7'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'ag7'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"           #
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  ag7:
    +meta:
      owner: 'alex '
      favorite_color: 'blue'  # Default color for the project
      maturity: 'low'  # Default maturity level for the project

    bronze:  # Define meta properties specific to bronze models
      +meta:
        owner: 'alex 01'
        favorite_color: 'green'  # Color for bronze models
        maturity: 'low'  # Maturity level for bronze models

    silver:      # Define meta properties specific to silver models
      +tags:
        - "when_needed"
      +meta:
        owner: 'alex 02'
        favorite_color: 'yellow'  # Color for silver models
        maturity: 'medium'  # Maturity level for silver models


vars:
  should_delete: true  # Set this to 'false' to disable deletion