name: dbt CI

on:
  pull_request:
    branches:
      - main

jobs:
  CI_job:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python (required for dbt)
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # Step 3: Install dbt globally
      - name: Install dbt
        run: |
          pip install dbt-postgres

      # Step 4: Run dbt debug to check the environment with secrets passed
      - name: Run dbt debug
        env:
          DBT_HOST: ${{ secrets.DBT_HOST }}
          DBT_USER: ${{ secrets.DBT_USER }}
          DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
        run: |
          dbt debug --profiles-dir ./ag7/ci_files

      # Step 5: Install dbt project dependencies with secrets passed
      - name: Run dbt deps
        env:
          DBT_HOST: ${{ secrets.DBT_HOST }}
          DBT_USER: ${{ secrets.DBT_USER }}
          DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
        run: |
          dbt deps --profiles-dir ./ag7/ci_files

      # Step 6: Run dbt build with secrets passed
      - name: Run dbt build
        env:
          DBT_HOST: ${{ secrets.DBT_HOST }}
          DBT_USER: ${{ secrets.DBT_USER }}
          DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
        run: |
          if [ -f "./manifest.json" ]; then
            dbt build -s 'state:modified+' --defer --state ./ --profiles-dir ./ag7/ci_files
          else
            dbt build --profiles-dir ./ag7/ci_files
          fi

      # (Optional) Step 7: Drop CI schema to clean up after the run with secrets passed
      - name: Drop CI schema
        env:
          DBT_HOST: ${{ secrets.DBT_HOST }}
          DBT_USER: ${{ secrets.DBT_USER }}
          DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
        run: |
          dbt run-operation drop_schema --args "{schema: ci_schema}" --profiles-dir ./ag7/ci_files
